Repository JA-yeong-eop-JA-moeu-JA/Jajaja_FE, pull requests merged in 2025-07, with the labels that each got.

#2 [Setting/#1] font, style 세팅
  .github/ISSUE_TEMPLATE/🐞-bugFix.md
  .github/ISSUE_TEMPLATE/📃-docs.md
  index.html
  public/logo.svg
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/logo.svg
  src/assets/react.svg
  src/index.css
  src/vite-env.d copy.ts
  tailwind.config.ts
Labels: ⚙️ setting

#4 [Setting/#3] 폴더 구조 및 라우터 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/index.css
  src/layouts/index.tsx
  src/pages/home.tsx
  src/pages/login.tsx
  src/pages/myPage.tsx
  src/pages/notice.tsx
  src/pages/payment.tsx
  src/routes/index.tsx
Labels: ⚙️ setting

#7 [Feat/#6] Modal 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/close.svg
  src/assets/icons/modalBar.svg
  src/components/common/modal.tsx
  src/components/modal/exampleModal.tsx
  src/index.css
  src/layouts/index.tsx
  src/pages/home.tsx
  src/stores/modalStore.ts
Labels: ✨ feat

#11 [Feat/#10] Checkbox 컴포넌트 구현
  FETCH_HEAD
  src/assets/icons/checkboxBlank.svg
  src/assets/icons/checkboxFill.svg
  src/components/checkbox/CheckboxAgreement.tsx
  src/components/checkbox/StatefulCheckbox.tsx
  src/components/checkbox/exampleAgreementCheckbox.tsx
  src/components/checkbox/exampleProductCheckbox.tsx
  src/components/common/checkbox.tsx
  src/pages/home.tsx
  src/stores/agreementCheckboxStore.ts
  src/stores/productCheckboxStore.ts
Labels: ✨ feat

#13 [Feat/#8] Button 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/button/button.tsx
  src/components/common/button/index.ts
  src/components/common/button/pageButton.tsx
  src/components/common/button/selectButton.tsx
  src/index.css
  src/pages/home.tsx
Labels: ✨ feat

#12 [Feat/#9] Header 및 BottomBar 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/back.svg
  src/assets/basket.svg
  src/assets/bell.svg
  src/assets/board.svg
  src/assets/cart.svg
  src/assets/category.svg
  src/assets/home.svg
  src/assets/my.svg
  src/assets/search.svg
  src/components/BottomBar.tsx
  src/components/HomeHeader.tsx
  src/components/PageHeader.tsx
  src/components/ProductHeader.tsx
  src/layouts/index.tsx
  src/pages/home.tsx
  src/pages/notice.tsx
  src/pages/payment.tsx
Labels: ✨ feat

#23 [Refactor/#21] button 컴포넌트 size 리팩토링
  src/components/common/button/button.tsx
  src/components/common/button/selectButton.tsx
  src/components/exampleButton.tsx
Labels: ♻️ refactor

#25 [Feat/#20] 홈 UI 구현
  package-lock.json
  package.json
  src/assets/icons/point.svg
  src/assets/icons/spin.svg
  src/assets/icons/star.svg
  src/assets/images/banner/1.svg
  src/assets/images/banner/2.svg
  src/assets/images/banner/3.svg
  src/assets/images/banner/4.svg
  src/assets/images/new/1.svg
  src/assets/images/new/2.svg
  src/assets/images/new/3.svg
  src/assets/images/new/4.svg
  src/assets/images/new/5.svg
  src/assets/images/new/6.svg
  src/assets/images/new/7.svg
  src/assets/images/new/8.svg
  src/assets/images/popular/1.svg
  src/assets/images/popular/2.svg
  src/assets/images/popular/3.svg
  src/assets/images/popular/4.svg
  src/assets/images/popular/5.svg
  src/assets/images/popular/6.svg
  src/assets/images/popular/7.svg
  src/assets/images/popular/8.svg
  src/assets/images/recommand/1.svg
  src/assets/images/recommand/2.svg
  src/assets/images/recommand/3.svg
  src/assets/images/recommand/4.svg
  src/assets/images/recommand/5.svg
  src/assets/images/recommand/6.svg
  src/assets/images/recommand/7.svg
  src/assets/images/recommand/8.svg
  src/components/common/SearchInput.tsx
  src/components/common/modal.tsx
  src/components/head_bottom/PageHeader.tsx
  src/components/home/banner.tsx
  src/components/home/new.tsx
  src/components/home/popular.tsx
  src/components/home/productCard.tsx
  src/components/home/recommand.tsx
  src/components/modal/homeModal.tsx
  src/constants/home/newList.ts
  src/constants/home/popularList.ts
  src/constants/home/recommandList.ts
  src/index.css
  src/layouts/index.tsx
  src/pages/home.tsx
  src/pages/onBoarding.tsx
  src/stores/modalStore.ts
  src/types/style.d.ts
  src/utils/crypto.ts
  src/utils/storage.ts
  vite.config.ts
Labels: ✨ feat

#31 [Refactor/#30] checkbox 컴포넌트 구조 리팩토링
  src/assets/icons/checkboxBlank.svg
  src/assets/icons/checkboxFill.svg
  src/components/common/checkbox.tsx
Labels: ♻️ refactor

#28 [Refactor/#27] Header 및 BottomBar UI 수정
  src/assets/bar_icons/bell.svg
  src/assets/bar_icons/cart.svg
  src/assets/bar_icons/home.svg
  src/assets/bar_icons/search.svg
  src/components/head_bottom/BottomBar.tsx
  src/components/head_bottom/HomeHeader.tsx
  src/components/head_bottom/PageHeader.tsx
  src/components/head_bottom/ProductHeader.tsx
  src/pages/home.tsx
  src/pages/myPage.tsx
Labels: ♻️ refactor

#39 [Feat/#38] 로그인 X 마이페이지 UI 구현
  src/assets/myPage/google.svg
  src/assets/myPage/kakao.svg
  src/assets/subLogo.svg
  src/components/common/button/button.tsx
  src/pages/login.tsx
  src/pages/mypage/myPage.tsx
  src/routes/index.tsx
Labels: ✨ feat, 🫧 add

#42 [Feat/#40] 약관동의 페이지 UI 구현
  src/constants/myPage/agreementList.ts
  src/pages/agreement.tsx
  src/routes/index.tsx
Labels: ✨ feat

#34 [Feat/#32] 검색창 화면 구현
  package-lock.json
  package.json
  src/assets/icons/back.svg
  src/assets/icons/delete.svg
  src/assets/icons/down.svg
  src/assets/icons/noResult.svg
  src/assets/icons/up.svg
  src/components/common/SearchInput.tsx
  src/components/search/menu.tsx
  src/components/search/tag.tsx
  src/constants/search/searchWord.ts
  src/constants/search/totalList.ts
  src/pages/home.tsx
  src/pages/onBoarding.tsx
  src/pages/search.tsx
  src/routes/index.tsx
Labels: ✨ feat

#41 [Feat/#35] 상품 상세 UI 구현
  package-lock.json
  package.json
  src/assets/bar_icons/back.svg
  src/assets/bar_icons/cart.svg
  src/assets/bar_icons/search.svg
  src/assets/icons/goUp.svg
  src/assets/icons/heart.svg
  src/assets/icons/heartFill.svg
  src/assets/icons/share.svg
  src/assets/icons/star.svg
  src/assets/images/product/1-1.svg
  src/assets/images/product/1-2.svg
  src/assets/images/product/1-3.svg
  src/assets/images/product/1-4.svg
  src/assets/images/product/1-5.svg
  src/assets/images/product/1-6.svg
  src/assets/images/product/1-7.svg
  src/assets/images/product/1-8.svg
  src/assets/images/product/1.svg
  src/assets/images/product/2.svg
  src/assets/images/product/3.svg
  src/assets/images/product/adv.svg
  src/assets/images/product/avatar1.svg
  src/assets/images/product/avatar2.svg
  src/assets/images/product/avatar3.svg
  src/assets/images/product/avatar4.svg
  src/assets/images/product/avatar5.svg
  src/assets/images/product/avatar6.svg
  src/assets/images/product/avatar7.svg
  src/components/head_bottom/ProductHeader.tsx
  src/components/home/productCard.tsx
  src/components/modal/homeModal.tsx
  src/components/product/reviewCard.tsx
  src/components/product/starRating.tsx
  src/constants/home/popularList.ts
  src/constants/home/recommandList.ts
  src/constants/product/reviews.ts
  src/constants/product/team.ts
  src/layouts/index.tsx
  src/pages/home.tsx
  src/pages/photoReview.tsx
  src/pages/product.tsx
  src/pages/review.tsx
  src/pages/search.tsx
  src/routes/index.tsx
Labels: ✨ feat

#60 [Feat/#59] 쿠폰 페이지 구현
  src/components/coupon/CouponCard.tsx
  src/constants/coupon/coupons.ts
  src/pages/coupon.tsx
  src/routes/index.tsx
  src/stores/couponStore.ts
Labels: ✨ feat

#55 [Feat/#54] 포인트 페이지 UI 구현
  src/components/pointCard.tsx
  src/constants/myPage/mainFunctions.ts
  src/mocks/pointData.ts
  src/pages/mypage/points.tsx
  src/routes/index.tsx
  src/types/point.ts
Labels: ✨ feat

#52 [Feat/#47] 리뷰 페이지 UI 및 관련 컴포넌트 구현
  src/assets/myPage/review/item/1.svg
  src/assets/myPage/review/item/2.svg
  src/assets/myPage/review/my/1.svg
  src/assets/myPage/review/my/2.svg
  src/assets/myPage/review/my/3.svg
  src/assets/myPage/review/my/4.svg
  src/assets/myPage/review/my/5.svg
  src/assets/myPage/review/receipt.svg
  src/assets/myPage/review/star.svg
  src/components/common/modal.tsx
  src/components/modal/reviewModal.tsx
  src/components/review/orderItem.tsx
  src/components/review/orderReviewList.tsx
  src/components/review/reviewItem.tsx
  src/constants/myPage/mainFunctions.ts
  src/mocks/orderData.ts
  src/mocks/reviewData.ts
  src/pages/mypage/myReview.tsx
  src/pages/mypage/writeReview.tsx
  src/routes/index.tsx
  src/stores/modalStore.ts
Labels: ✨ feat

#62 [Feat/#56] 리뷰 작성 페이지 UI 구현
  src/assets/myPage/review/close.svg
  src/assets/myPage/review/plus.svg
  src/assets/myPage/review/starLine.svg
  src/components/review/imageUploader.tsx
  src/components/review/orderItem.tsx
  src/components/review/orderReviewList.tsx
  src/components/review/reviewStarRating.tsx
  src/mocks/orderData.ts
  src/pages/mypage/writeReview.tsx
  src/routes/index.tsx
Labels: ✨ feat

#57 [Feat/#37] 장바구니 화면 구현
  src/assets/shoppingCart.svg
  src/components/common/checkbox.tsx
  src/components/head_bottom/BottomBar.tsx
  src/components/modal/homeModal.tsx
  src/components/modal/reviewModal.tsx
  src/components/review/orderItem.tsx
  src/components/review/reviewItem.tsx
  src/pages/feedback/NotFoundPage.tsx
  src/pages/shoppingCart.tsx
  src/routes/index.tsx
  src/stores/modalStore.ts
Labels: ✨ feat

#50 [Feat/#48] 제품 상세 모달 UI 구현
  eslint.config.mjs
  prettier/default.mjs
  src/assets/icons/cartBtn.svg
  src/assets/icons/delete.svg
  src/assets/icons/down.svg
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/components/common/modal.tsx
  src/components/modal/dropDown.tsx
  src/components/modal/optionModal.tsx
  src/components/search/tag.tsx
  src/constants/product/options.ts
  src/pages/product.tsx
  src/pages/search.tsx
  src/stores/modalStore.ts
Labels: ✨ feat

#68 [Feat/#67] 교환/반품 접수 UI 구현
  src/assets/ChevronRight2.svg
  src/assets/icons/box.svg
  src/components/board/HorizontalProductCard.tsx
  src/components/common/FeedbackPage.tsx
  src/components/head_bottom/BottomBar.tsx
  src/components/head_bottom/PageHeader.tsx
  src/components/modal/confirmModal.tsx
  src/components/orderDetail/OrderList.tsx
  src/components/orderDetail/orderProductList.tsx
  src/components/orderDetail/paymentInfo.tsx
  src/components/orderDetail/returnInfo.tsx
  src/constants/myPage/mainFunctions.ts
  src/constants/product/statusColorMap.ts
  src/mocks/orderData.ts
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/board.tsx
  src/pages/categoryPage.tsx
  src/pages/deliveryInfo.tsx
  src/pages/feedback/NotFoundPage.tsx
  src/pages/orderDetailPersonal.tsx
  src/pages/orderDetailTeam.tsx
  src/pages/orderListPage.tsx
  src/routes/index.tsx
Labels: ✨ feat

#81 [Feat/#69] 배송지 추가 화면 구현
  src/components/common/InputField.tsx
  src/pages/addAddress.tsx
  src/pages/shoppingCart.tsx
  src/routes/index.tsx
Labels: ✨ feat

#74 [Refactor/#37] 장바구니 UI 수정
  src/assets/bar_icons/cartFill.svg
  src/components/common/modal.tsx
  src/components/head_bottom/BottomBar.tsx
  src/components/modal/optionModal.tsx
  src/components/modal/shoppingCartModal.tsx
  src/components/review/orderItem.tsx
  src/pages/shoppingCart.tsx
  src/stores/modalStore.ts
Labels: ♻️ refactor

#92 [Setting] axios 환경세팅
  .gitignore
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/apis/myPage/myPage.ts
  src/constants/querykeys/queryKeys.ts
  src/hooks/customQuery.ts
  src/hooks/myPage/useUserInfo.ts
  src/main.tsx
  src/pages/mypage/myPage.tsx
  src/types/common.ts
  src/types/member/TGetUserInfo.ts
  vite.config.ts
Labels: ⚙️ setting

#96 setting: 배포 환경 세팅
  .github/workflows/main.yaml
  vercel.json
Labels: ⚙️ setting
