Repository JA-yeong-eop-JA-moeu-JA/Jajaja_FE, pull requests merged in 2025-08, with the labels that each got.

#111 fix: 프로필 이미지 크기 고정
  src/pages/mypage/myPage.tsx
Labels: 🐛 fix

#113 [Feat] 홈 상품 리스트 api 연결
  src/apis/home/product.ts
  src/components/home/new.tsx
  src/components/home/popular.tsx
  src/components/home/productCard.tsx
  src/components/home/recommand.tsx
  src/constants/querykeys/queryKeys.ts
  src/constants/search/totalList.ts
  src/hooks/home/useGetProduct.ts
  src/pages/home.tsx
  src/pages/mypage/myPage.tsx
  src/pages/onBoarding.tsx
  src/pages/product.tsx
  src/pages/review.tsx
  src/pages/search.tsx
  src/types/home/product.ts
  src/utils/storage.ts
Labels: ✨ feat

#117 [Feat] product 상세 api 연결
  src/apis/product/product.ts
  src/components/product/reviewCard.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/product/useGetProductDetail.ts
  src/pages/product.tsx
  src/pages/review.tsx
  src/types/product/product.ts
  src/utils/time.ts
Labels: ✨ feat

#121 [Feat] option list api 연결
  src/apis/product/option.ts
  src/components/modal/dropDown.tsx
  src/components/modal/optionModal.tsx
  src/components/modal/shoppingCartModal.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/product/useGetOption.ts
  src/types/product/option.ts
Labels: ✨ feat

#123 [Feat/#112] 쿠폰 api 연동
  package-lock.json
  package.json
  src/apis/coupon/getCoupons.ts
  src/assets/myPage/defaultProfile.svg
  src/components/coupon/CouponCard.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/coupon/useInfiniteCoupons.ts
  src/pages/coupon.tsx
  src/pages/mypage/coupons.tsx
  src/pages/mypage/profile.tsx
  src/types/TPage.ts
  src/types/coupon/TGetCoupons.ts
Labels: ✨ feat, 🫧 add, 🧹 chore

#127 [Feat/#125] 로그아웃 api 연동
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/hooks/auth/useLogout.ts
  src/hooks/myPage/usePatchUserInfo.ts
  src/pages/mypage/myPage.tsx
Labels: ✨ feat

#129 [Feat/#128] 알림 페이지 api 연동
  src/apis/notifications/notifications.ts
  src/components/notiCard.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/notifications/useGetNotiList.ts
  src/hooks/notifications/useGetNotiUnread.ts
  src/hooks/notifications/usePatchNotiRead.ts
  src/hooks/notifications/usePatchNotiReadAll.ts
  src/mocks/notiData.ts
  src/mocks/profileData.ts
  src/pages/notifications.tsx
  src/types/notifications/TGetNotiList.ts
  src/types/notifications/TGetNotiUnread.ts
Labels: ✨ feat

#132 [Feat] 리뷰 상세 조회 api 구현
  src/apis/review/review.ts
  src/components/product/reviewCard.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/review/useGetInfinite.ts
  src/hooks/review/useGetReviewDetail.ts
  src/pages/review.tsx
  src/types/product/product.ts
  src/types/review/review.ts
Labels: ✨ feat

#136 [Feat] 팀 생성 api 연결
  src/apis/product/makeTeam.ts
  src/components/modal/dropDown.tsx
  src/components/modal/optionModal.tsx
  src/hooks/product/useMakeTeam.ts
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/product.tsx
  src/types/product/makeTeam.ts
Labels: ✨ feat

#140 [Feat] 팀 참여 api 연결
  src/apis/product/joinTeam.ts
  src/apis/product/makeTeam.ts
  src/hooks/product/useGetProductDetail.ts
  src/hooks/product/useJoinTeam.ts
  src/hooks/product/useMakeTeam.ts
  src/pages/product.tsx
  src/types/product/joinTeam.ts
Labels: ✨ feat

#142 [Fix] 디자인 QA 반영
  src/assets/icons/cartBtn.svg
  src/components/common/SearchInput.tsx
  src/components/common/modal.tsx
  src/components/modal/homeModal.tsx
  src/components/modal/optionModal.tsx
  src/pages/home.tsx
  src/pages/onBoarding.tsx
  src/pages/product.tsx
  src/pages/search.tsx
Labels: 🐛 fix

#147 [Feat/#124] 포인트 api 연동
  src/apis/points/getPoints.ts
  src/components/pointCard.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/points/useInfinitePoints.ts
  src/pages/mypage/points.tsx
  src/types/points/TGetPoints.ts
Labels: ✨ feat

#138 [Feat/#85] Board 게시판 API 연동
  src/apis/axiosInstance.ts
  src/apis/board/reviewBoard.ts
  src/apis/board/team.ts
  src/apis/reviews.ts
  src/components/board/HorizontalProductCard.tsx
  src/components/board/ReviewCard.tsx
  src/components/modal/optionModal.tsx
  src/constants/bottomBar/teamRecruit.ts
  src/constants/querykeys/queryKeys.ts
  src/hooks/board/useReviews.ts
  src/hooks/board/useTeamProducts.ts
  src/mocks/teamRecruit.ts
  src/pages/board.tsx
  src/pages/categoryPage.tsx
  src/pages/onBoarding.tsx
  src/pages/product.tsx
  src/pages/review.tsx
  src/types/board/reviewBoard.ts
  src/types/board/team.ts
  src/types/review.ts
Labels: ✨ feat

#151 [Feat/#148] 리뷰 페이지 api 연동
  src/apis/points/getPoints.ts
  src/apis/review/myReview.ts
  src/apis/s3/s3.ts
  src/components/orderDetail/OrderList.tsx
  src/components/orderDetail/orderProductList.tsx
  src/components/review/imageUploader.tsx
  src/components/review/orderItem.tsx
  src/components/review/orderReviewList.tsx
  src/components/review/reviewItem.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/myPage/usePatchUserInfo.ts
  src/hooks/review/useDeleteReivew.ts
  src/hooks/review/useGetMyReview.ts
  src/hooks/review/useGetReviewable.ts
  src/hooks/review/usePostReview.ts
  src/hooks/s3/useImageUploader.ts
  src/hooks/s3/usePostUpload.ts
  src/hooks/s3/usePostUploadList.ts
  src/hooks/s3/usePutUpload.ts
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/mypage/myReview.tsx
  src/pages/mypage/profile.tsx
  src/pages/mypage/writeReview.tsx
  src/pages/payment.tsx
  src/pages/shoppingCart.tsx
  src/routes/index.tsx
  src/types/TPage.ts
  src/types/points/TGetPoints.ts
  src/types/review/myReview.ts
  src/types/s3/TPostUpload.ts
Labels: ✨ feat

#154 [Fix/#152] 디자인 QA 반영
  src/apis/notifications/notifications.ts
  src/components/common/button/selectButton.tsx
  src/components/loading.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/TeamModal.tsx
  src/components/modal/exampleModal.tsx
  src/components/modal/reviewModal.tsx
  src/constants/myPage/benefitList.ts
  src/constants/myPage/mainFunctions.ts
  src/hooks/notifications/useGetNotiList.ts
  src/hooks/notifications/useGetNotiUnread.ts
  src/hooks/notifications/usePatchNotiRead.ts
  src/hooks/notifications/usePatchNotiReadAll.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/login.tsx
  src/pages/mypage/coupons.tsx
  src/pages/mypage/points.tsx
  src/pages/mypage/profile.tsx
  src/pages/notifications.tsx
  src/stores/modalStore.ts
  src/types/notifications/TGetNotiList.ts
Labels: 🐛 fix

#156 [Fix/#155] 리뷰 페이지 api 수정
  src/components/review/orderItem.tsx
  src/components/review/reviewItem.tsx
  src/pages/mypage/writeReview.tsx
  src/types/board/reviewBoard.ts
  src/types/product/product.ts
  src/types/review/myReview.ts
  src/types/review/review.ts
Labels: 🐛 fix

#158 [Fix/#155] 리뷰 페이지 api 수정-2
  src/components/review/imageUploader.tsx
  src/components/review/orderItem.tsx
  src/components/review/orderReviewList.tsx
  src/pages/mypage/myReview.tsx
  src/pages/mypage/writeReview.tsx
  src/stores/reviewImageStore.ts
Labels: 🐛 fix

#160 [Feat/#159] 결제 페이지 쿠폰 선택 API 연동
  src/apis/axiosInstance.ts
  src/apis/coupon/getCoupons.ts
  src/hooks/coupon/useCoupons.ts
  src/hooks/coupon/useInfiniteCoupons.ts
  src/pages/coupon.tsx
  src/pages/payment.tsx
  src/types/coupon/TGetCoupons.ts
  vite.config.ts
Labels: ✨ feat

#166 [Feat] 상품 검색 api 연결
  src/components/search/tag.tsx
  src/hooks/customQuery.ts
  src/hooks/search/useDeleteRecent.ts
  src/hooks/search/useKeywordProduct.ts
  src/pages/search.tsx
Labels: ✨ feat

#165 [Feat/#99] 장바구니 CRUD API 연동
  src/apis/cart/cart.ts
  src/components/modal/dropDown.tsx
  src/components/modal/shoppingCartModal.tsx
  src/components/review/orderItem.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/cart/useCartQuery.ts
  src/hooks/product/useGetOption.ts
  src/pages/shoppingCart.tsx
  src/types/cart/TCart.ts
Labels: ✨ feat

#177 [Refactor] 회원 비회원 분기 처리
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/members/members.ts
  src/apis/search/recent.ts
  src/components/common/SearchInput.tsx
  src/components/common/modal.tsx
  src/components/home/banner.tsx
  src/components/modal/optionModal.tsx
  src/components/product/reviewCard.tsx
  src/components/search/tag.tsx
  src/context/AuthContext.tsx
  src/hooks/category/useCategoryProduct.ts
  src/hooks/home/useGetProduct.ts
  src/hooks/product/useGetProductDetail.ts
  src/hooks/search/useGetRecent.ts
  src/hooks/search/useKeywordProduct.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/home.tsx
  src/pages/onBoarding.tsx
  src/pages/product.tsx
  src/pages/search.tsx
  src/routes/index.tsx
  src/types/category.ts
  src/types/search/search.ts
  src/utils/storage.ts
Labels: 🐛 fix, ♻️ refactor

#181 [Deploy] 배포
  src/pages/search.tsx
Labels: 🌎 deploy

#182 [Refactor/#175] 쿠폰 무한 스크롤 적용 및 적용/수정 기능 리팩토링
  src/apis/address/address.ts
  src/apis/coupon/getCoupons.ts
  src/components/coupon/CouponCard.tsx
  src/components/head_bottom/ProductHeader.tsx
  src/constants/querykeys/queryKeys.ts
  src/hooks/address/useAddress.ts
  src/hooks/coupon/useCoupons.ts
  src/hooks/coupon/useInfiniteCoupons.ts
  src/pages/addressChange.tsx
  src/pages/coupon.tsx
  src/pages/payment.tsx
  src/pages/shoppingCart.tsx
  src/types/address/TAddress.ts
  src/types/cart/TCart.ts
  src/types/coupon/TGetCoupons.ts
Labels: ✨ feat

#184 [Refactor] search 부분 api 수정 반영
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/members/members.ts
  src/apis/search/recent.ts
  src/context/AuthContext.tsx
  src/hooks/search/useGetRecent.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/search.tsx
  src/routes/index.tsx
Labels: 🐛 fix, ♻️ refactor

#185 [Deploy] 배포
  src/apis/address/address.ts
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/coupon/getCoupons.ts
  src/apis/members/members.ts
  src/apis/search/recent.ts
  src/components/coupon/CouponCard.tsx
  src/components/head_bottom/ProductHeader.tsx
  src/constants/querykeys/queryKeys.ts
  src/context/AuthContext.tsx
  src/hooks/address/useAddress.ts
  src/hooks/coupon/useCoupons.ts
  src/hooks/coupon/useInfiniteCoupons.ts
  src/hooks/search/useGetRecent.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/addressChange.tsx
  src/pages/coupon.tsx
  src/pages/payment.tsx
  src/pages/search.tsx
  src/pages/shoppingCart.tsx
  src/routes/index.tsx
  src/types/address/TAddress.ts
  src/types/cart/TCart.ts
  src/types/coupon/TGetCoupons.ts
Labels: 🌎 deploy

#188 [Bug/#187] /me 무한 재호출 버그 수정
  src/apis/auth/auth.ts
  src/hooks/myPage/useUserInfo.ts
  src/layouts/ProtectedLayout.tsx
Labels: 🐛 fix

#192 [Fix] 홈, 검색창 피드백 반영
  src/components/common/SearchInput.tsx
  src/components/modal/homeModal.tsx
  src/pages/search.tsx
Labels: 🐛 fix

#196 [Deploy] 배포
  src/pages/board.tsx
  src/pages/categoryPage.tsx
  src/pages/home.tsx
  src/pages/product.tsx
  src/pages/search.tsx
Labels: 🌎 deploy

#201 [Feat/#162] 실시간 구독 api 연동
  src/apis/notifications/notifications.ts
  src/components/Subscriber.tsx
  src/components/common/modal.tsx
  src/components/head_bottom/HomeHeader.tsx
  src/components/modal/TeamModal.tsx
  src/components/notiCard.tsx
  src/hooks/notifications/useGetNotiUnread.ts
  src/layouts/index.tsx
  src/stores/modalStore.ts
  src/types/notifications/TGetNotiList.ts
Labels: ✨ feat

#202 [Refactor] UI 피드백 반영
  src/assets/bar_icons/basket.svg
  src/assets/bar_icons/cartFill.svg
  src/components/head_bottom/ProductHeader.tsx
  src/components/modal/optionModal.tsx
  src/components/orderDetail/OrderList.tsx
  src/components/orderDetail/orderProductList.tsx
  src/components/orderDetail/returnInfo.tsx
  src/constants/product/statusColorMap.ts
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/board.tsx
  src/pages/home.tsx
  src/pages/mypage/myPage.tsx
  src/pages/orderDetailPersonal.tsx
  src/pages/product.tsx
  src/pages/search.tsx
  src/types/order/detailPersonal.ts
Labels: 🐛 fix, ♻️ refactor

#207 [Fix] svg 사이즈 변경
  src/components/modal/optionModal.tsx
Labels: 🐛 fix

#206 [Deploy] 배포
  src/apis/notifications/notifications.ts
  src/assets/bar_icons/basket.svg
  src/assets/bar_icons/cartFill.svg
  src/components/Subscriber.tsx
  src/components/common/button/button.tsx
  src/components/common/modal.tsx
  src/components/head_bottom/HomeHeader.tsx
  src/components/head_bottom/ProductHeader.tsx
  src/components/modal/TeamModal.tsx
  src/components/modal/optionModal.tsx
  src/components/modal/shoppingCartModal.tsx
  src/components/notiCard.tsx
  src/components/orderDetail/OrderList.tsx
  src/components/orderDetail/orderProductList.tsx
  src/components/orderDetail/returnInfo.tsx
  src/constants/product/statusColorMap.ts
  src/hooks/coupon/useCoupons.ts
  src/hooks/notifications/useGetNotiUnread.ts
  src/layouts/index.tsx
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/board.tsx
  src/pages/feedback/paymentStatus.tsx
  src/pages/home.tsx
  src/pages/mypage/myPage.tsx
  src/pages/orderDetailPersonal.tsx
  src/pages/payment.tsx
  src/pages/product.tsx
  src/pages/search.tsx
  src/pages/shoppingCart.tsx
  src/stores/modalStore.ts
  src/types/cart/TCart.ts
  src/types/coupon/TGetCoupons.ts
  src/types/notifications/TGetNotiList.ts
  src/types/order/detailPersonal.ts
  src/utils/storage.ts
Labels: 🌎 deploy

#217 [Refactor] 검색 결과 무한 스크롤 적용
  src/hooks/home/useGetProduct.ts
  src/hooks/search/useKeywordProduct.ts
  src/pages/home.tsx
  src/pages/search.tsx
  src/types/search/search.ts
Labels: ✨ feat, ♻️ refactor

#224 [Refactor/#218] 평가 점수를 위한 코드 리팩토링
  src/App.tsx
  src/apis/members/members.ts
  src/components/coupon/CouponCardSkeleton.tsx
  src/components/head_bottom/BottomBar.tsx
  src/components/notiCardSkeleton.tsx
  src/components/pointCardSkeleton.tsx
  src/components/review/orderReviewListSkeleton.tsx
  src/components/review/reviewItemSkeleton.tsx
  src/constants/myPage/agreementList.ts
  src/context/AuthContext.tsx
  src/hooks/coupon/useInfiniteCoupons.ts
  src/hooks/members/usePatchUserInfo.ts
  src/hooks/members/usePostAgree.ts
  src/hooks/members/useUserInfo.ts
  src/hooks/notifications/useGetNotiUnread.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/agreement.tsx
  src/pages/board.tsx
  src/pages/mypage/coupons.tsx
  src/pages/mypage/myPage.tsx
  src/pages/mypage/myReview.tsx
  src/pages/mypage/points.tsx
  src/pages/mypage/profile.tsx
  src/pages/notifications.tsx
  src/pages/payment.tsx
  src/routes/index.tsx
Labels: ✨ feat, ♻️ refactor

#228 [Deploy] 배포
  src/pages/agreement.tsx
  src/pages/board.tsx
Labels: 🌎 deploy

#229 fix: 페이지 리사이징 수정
  src/pages/agreement.tsx
Labels: 🐛 fix

#232 [Deploy] 배포
  src/apis/axiosInstance.ts
  src/apis/cart/cart.ts
  src/components/common/SearchInput.tsx
  src/components/modal/optionModal.tsx
  src/components/modal/shoppingCartModal.tsx
  src/context/AuthContext.tsx
  src/hooks/cart/useAddMultipleToCart.ts
  src/hooks/cart/useAddToCart.ts
  src/hooks/cart/useCart.ts
  src/hooks/product/useMakeTeam.ts
  src/hooks/search/useKeywordProduct.ts
  src/pages/agreement.tsx
  src/pages/login.tsx
  src/pages/mypage/coupons.tsx
  src/pages/mypage/myDetailPage.tsx
  src/pages/mypage/myPage.tsx
  src/pages/mypage/myReview.tsx
  src/pages/mypage/points.tsx
  src/pages/mypage/writeReview.tsx
  src/pages/notifications.tsx
  src/pages/payment.tsx
  src/pages/product.tsx
  src/pages/shoppingCart.tsx
  src/stores/modalStore.ts
  src/types/cart/TCart.ts
  src/types/product/makeTeam.ts
  src/utils/cartStorage.ts
  src/utils/storage.ts
Labels: 🌎 deploy

#238 [Add/#230] 환경 변수 테스트
  src/hooks/payment/useTossPayments.ts
Labels: 🧹 chore

#242 [Fix] 회원가입시 업종 저장
  src/pages/agreement.tsx
  src/pages/home.tsx
  src/utils/storage.ts
Labels: 🐛 fix

#245 [Fix] 회원가입 성공시 업종 저장
  src/hooks/members/usePostAgree.ts
  src/pages/agreement.tsx
Labels: 🐛 fix

#246 [Deploy] 배포
  src/hooks/members/usePostAgree.ts
  src/pages/agreement.tsx
Labels: 🐛 fix

#251 [Fix/#250] 리뷰 작성 버그 수정
  src/apis/s3/s3.ts
  src/components/review/imageUploader.tsx
  src/hooks/payment/useTossPayments.ts
  src/hooks/review/useDeleteReivew.ts
  src/hooks/review/usePostReview.ts
  src/hooks/s3/useImageUploader.ts
  src/mocks/teamRecruit.ts
  src/pages/mypage/myReview.tsx
  src/pages/mypage/profile.tsx
  src/pages/mypage/writeReview.tsx
  src/types/s3/TPostUpload.ts
Labels: 🐛 fix

#255 [Deploy] 배포
  src/components/Subscriber.tsx
Labels: 🌎 deploy

#257 [Fix/#248] 쿠폰 페이지 / 결제 플로우에서 발생하는 버그 수정
  package-lock.json
  package.json
  src/components/coupon/CouponCard.tsx
  src/components/modal/optionModal.tsx
  src/components/review/orderItem.tsx
  src/hooks/coupon/useCoupons.ts
  src/hooks/payment/usePaymentConfirm.ts
  src/hooks/payment/usePaymentStatus.ts
  src/hooks/product/useJoinTeam.ts
  src/pages/ApplyReturnOrExchange.tsx
  src/pages/coupon.tsx
  src/pages/feedback/PaymentStatusHandler.tsx
  src/pages/feedback/exchangeOk.tsx
  src/pages/feedback/paymentStatus.tsx
  src/pages/feedback/paymentStatusWrapper.tsx
  src/pages/feedback/returnOk.tsx
  src/pages/mypage/coupons.tsx
  src/pages/payment.tsx
  src/types/cart/TCart.ts
  src/types/coupon/TGetCoupons.ts
Labels: 🐛 fix

#262 [Deploy] 배포
  src/components/product/reviewCard.tsx
Labels: 🌎 deploy

#271 [Fix/#267] 모바일 환경 쿠폰 스크롤 수정
  src/pages/coupon.tsx
  src/pages/payment.tsx
Labels: 🐛 fix

#274 [Fix] 정렬 오류 수정
  src/pages/photoReview.tsx
  src/pages/review.tsx
Labels: 🐛 fix

#275 [Deploy] 배포
  src/pages/photoReview.tsx
  src/pages/review.tsx
Labels: 🌎 deploy

#278 [Fix/#270] 요청사항 반영
  src/components/head_bottom/HomeHeader.tsx
  src/layouts/ProtectedLayout.tsx
  src/pages/mypage/profile.tsx
Labels: 🐛 fix

#300 [Fix] 검색 결과 없음 UI 복구
  src/pages/search.tsx
Labels: 🐛 fix
